app = "impact-lab-cdmx"
primary_region = "qro"

[build]

[env]
  PORT = "8080"
  MARIMO_NOTEBOOK = "notebooks/tus_100_pesos.py"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
